# Generated by Django 4.1.7 on 2023-03-06 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=150)),
                ('valor', models.IntegerField()),
                ('date_create', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('dato_agred', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitioWeb.producto')),
            ],
        ),
    ]
